version: 0.2

phases:
  install:
    commands:
      - cd "Pipeline CI & CD for static website with CV"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 746669194945.dkr.ecr.eu-west-3.amazonaws.com
      - IMAGE_URI=746669194945.dkr.ecr.eu-west-3.amazonaws.com/cv-website:latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI

artifacts:
  files:
    - '**/*'
