version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-west-3)
      - IMAGE_URI=746669194945.dkr.ecr.eu-west-3.amazonaws.com/cv-website:latest
      - echo IMAGE_URI=$IMAGE_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
      - docker tag $IMAGE_URI $IMAGE_URI
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"cv-service","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
